plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'wyvern.chat.ChatServer'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    manifest {
        attributes 'Main-Class': 'wyvern.chat.ChatServer'
    }
}
